export const UI_MESSAGES = {
  zh: {
    'ui.enemySpeed': '移速',
    'ui.language': '語言', 'ui.brand': '星域防線', 'ui.game': '對局', 'ui.home': '首頁', 'ui.lead': '守衛人類星際殖民地的能源核心，阻止機械群沿地表通道與空中航道進攻。', 'ui.start': '開始遊戲', 'ui.audioHint': '🔈 點擊任意處或按任意鍵開啟音樂與音效',
    'ui.music': '音樂', 'ui.sfx': '音效', 'ui.musicVolume': '音樂音量', 'ui.sfxVolume': '音效音量', 'ui.selectTower': '選塔', 'ui.cancel': '取消', 'ui.nextWave': '開始下一波', 'ui.pause': '暫停', 'ui.speed': '倍速', 'ui.install': '安裝為應用程式', 'ui.offlineReady': '已可離線遊玩',
    'ui.mapSelect': '地圖選擇', 'ui.chooseMap': '選擇地圖', 'ui.wavesTitle': '波次', 'ui.baseTitle': '♥ 基地', 'ui.resourcesTitle': '資源', 'ui.pauseResume': '暫停／繼續（P）', 'ui.startNextWave': '開始下一波（Space）', 'ui.mapButton': '地圖', 'ui.towerMenu': '塔選單', 'ui.stars': '{count} 星',
    'ui.cost': '造價', 'ui.target': '目標', 'ui.detectAir': '（偵測：空地）', 'ui.range': '射程', 'ui.attackRange': '攻擊 {range} 格／偵測 {detect} 格', 'ui.rangeValue': '{range} 格', 'ui.damage': '傷害', 'ui.damageRate': '{damage}／{interval} 秒', 'ui.droneDamageRate': '{damage}／{interval} 秒（每機，{drones} 架）', 'ui.effect': '效果', 'ui.appearance': '外觀', 'ui.level': '等級', 'ui.invested': 'Lv{level} / Lv{max}（已投入 {amount} CR）', 'ui.nextLevel': '下一級', 'ui.nextStats': '傷害 {damage}→{nextDamage}、射程 {range}→{nextRange} 格',
    'ui.groundShort': '地', 'ui.airShort': '空', 'ui.bothShort': '空地', 'ui.selected': '選取中', 'ui.movingLevel': '移動中・Lv{level}', 'ui.builtLevel': '已建造・Lv{level}', 'ui.placeHint': '左鍵放置（2×2 格）・Shift＋左鍵連續放置・Esc／右鍵取消', 'ui.moveHint': '左鍵選擇新位置（移動費 {cost} CR；保留等級，移動後立即可攻擊）・V／Esc／右鍵取消', 'ui.maxLevel': '已達最高等級', 'ui.upgrade': '升級至 Lv{level}（{cost} CR）', 'ui.move': '移動 {cost} CR', 'ui.sell': '出售 +{refund} CR', 'ui.instructions': '操作說明', 'ui.instructionsBuild': '從上方選塔（或按 1–0、-、=），在可建塔格（方格底紋）上點擊放置；塔佔 2×2 格。', 'ui.instructionsRoutes': '實心路面＝地面路線；懸空虛線＋投影＝空中航道；◇＝地空共用段。指向入口可高亮整條路線。', 'ui.instructionsTerrain': '斜線＝邊陲荒地、紋路色塊＝主題地形，皆不可建塔。隱形敵人需 T05 偵測 6.0 格內才會顯形。', 'ui.instructionsKeys': 'Space 下一波・P 暫停・F 倍速・U 升級・V 移動・S 出售選取的塔・M 音樂・N 音效',
    'ui.pausedStatus': '⏸ 已暫停 — 仍可建塔；按 P 或速度按鈕繼續', 'ui.waveStartFirst': '開始第 1 波', 'ui.waveFinal': '最終波', 'ui.waveStartNext': '開始下一波', 'ui.audioOn': '開', 'ui.audioOff': '關', 'ui.audioToggleTitle': '{name}：{state}（{key} 切換）', 'ui.audioVolumeTitle': '{name}音量 {percent}%',
    'ui.hp': '生命', 'ui.shield': '護盾', 'ui.type': '類型', 'ui.childType': '{type}（分裂子體）', 'ui.speedRate': '{speed} 格／秒', 'ui.reward': '獎勵', 'ui.childReward': '0 CR（子體）', 'ui.route': '路線 {id}', 'ui.airRoute': '空中航道（虛線）', 'ui.groundRoute': '地面路線（實心路面）', 'ui.routeHighlight': '已高亮完整行進路徑',
    'ui.errFunds': '資源不足', 'ui.errEnded': '對局已結束', 'ui.errMove': '無法移到此處', 'ui.errBuild': '此處不可建塔', 'ui.errMax': '已達最高等級', 'ui.sold': '已出售，退還 {refund} CR', 'ui.victory': '✔ 勝利 VICTORY', 'ui.defeat': '✖ 失敗 DEFEAT', 'ui.downloadCard': '下載戰果分享卡', 'ui.restart': '重新開始', 'ui.backMaps': '返回地圖選擇', 'ui.downloadError': '下載失敗：{message}。戰果已保留，請再試一次。'
  },
  en: {
    'ui.enemySpeed': 'Move speed',
    'ui.language': 'Language', 'ui.brand': 'Starward Bastion', 'ui.game': 'Battle', 'ui.home': 'Home', 'ui.lead': 'Defend the energy core of humanity’s interstellar colonies from machines advancing along ground routes and air lanes.', 'ui.start': 'Start Game', 'ui.audioHint': '🔈 Click anywhere or press any key to enable music and sound effects',
    'ui.music': 'Music', 'ui.sfx': 'SFX', 'ui.musicVolume': 'Music volume', 'ui.sfxVolume': 'SFX volume', 'ui.selectTower': 'Select tower', 'ui.cancel': 'Cancel', 'ui.nextWave': 'Next Wave', 'ui.pause': 'Pause', 'ui.speed': 'Speed', 'ui.install': 'Install App', 'ui.offlineReady': 'Ready to play offline',
    'ui.mapSelect': 'Map Selection', 'ui.chooseMap': 'Choose a Map', 'ui.wavesTitle': 'Wave', 'ui.baseTitle': '♥ Base', 'ui.resourcesTitle': 'Resources', 'ui.pauseResume': 'Pause / resume (P)', 'ui.startNextWave': 'Start next wave (Space)', 'ui.mapButton': 'Maps', 'ui.towerMenu': 'Tower menu', 'ui.stars': '{count} stars',
    'ui.cost': 'Cost', 'ui.target': 'Target', 'ui.detectAir': ' (detects cloaked)', 'ui.range': 'Range', 'ui.attackRange': 'Attack {range} tiles / detect {detect} tiles', 'ui.rangeValue': '{range} tiles', 'ui.damage': 'Damage', 'ui.damageRate': '{damage} / {interval}s', 'ui.droneDamageRate': '{damage} / {interval}s (each, {drones} drones)', 'ui.effect': 'Effect', 'ui.appearance': 'Profile', 'ui.level': 'Level', 'ui.invested': 'Lv{level} / Lv{max} ({amount} CR invested)', 'ui.nextLevel': 'Next level', 'ui.nextStats': 'Damage {damage}→{nextDamage}, range {range}→{nextRange} tiles',
    'ui.groundShort': 'G', 'ui.airShort': 'A', 'ui.bothShort': 'G/A', 'ui.selected': 'Selected', 'ui.movingLevel': 'Moving · Lv{level}', 'ui.builtLevel': 'Built · Lv{level}', 'ui.placeHint': 'Left-click to place (2×2 tiles) · Shift-click to keep placing · Esc/right-click to cancel', 'ui.moveHint': 'Left-click a new location ({cost} CR; level retained, can attack immediately) · V/Esc/right-click to cancel', 'ui.maxLevel': 'Max level reached', 'ui.upgrade': 'Upgrade to Lv{level} ({cost} CR)', 'ui.move': 'Move {cost} CR', 'ui.sell': 'Sell +{refund} CR', 'ui.instructions': 'Instructions', 'ui.instructionsBuild': 'Choose a tower above (or press 1–0, - or =), then click a buildable tile (checkered floor). Towers occupy 2×2 tiles.', 'ui.instructionsRoutes': 'Solid road = ground route; dashed elevated path + shadow = air lane; ◇ = shared ground/air segment. Hover an entrance to highlight its full route.', 'ui.instructionsTerrain': 'Hatching marks the frontier and patterned tiles mark themed terrain; neither is buildable. Cloaked enemies are revealed by T05 within 6.0 tiles.', 'ui.instructionsKeys': 'Space next wave · P pause · F speed · U upgrade · V move · S sell selected tower · M music · N SFX',
    'ui.pausedStatus': '⏸ Paused — you can still build; press P or a speed button to resume', 'ui.waveStartFirst': 'Start Wave 1', 'ui.waveFinal': 'Final Wave', 'ui.waveStartNext': 'Next Wave', 'ui.audioOn': 'On', 'ui.audioOff': 'Off', 'ui.audioToggleTitle': '{name}: {state} (press {key} to toggle)', 'ui.audioVolumeTitle': '{name} volume {percent}%',
    'ui.hp': 'Health', 'ui.shield': 'Shield', 'ui.type': 'Type', 'ui.childType': '{type} (split child)', 'ui.speedRate': '{speed} tiles/s', 'ui.reward': 'Reward', 'ui.childReward': '0 CR (child)', 'ui.route': 'Route {id}', 'ui.airRoute': 'Air lane (dashed)', 'ui.groundRoute': 'Ground route (solid road)', 'ui.routeHighlight': 'Full route highlighted',
    'ui.errFunds': 'Insufficient resources', 'ui.errEnded': 'Game has ended', 'ui.errMove': 'Cannot move there', 'ui.errBuild': 'Cannot build here', 'ui.errMax': 'Maximum level reached', 'ui.sold': 'Sold, refunded {refund} CR', 'ui.victory': '✔ Victory', 'ui.defeat': '✖ Defeat', 'ui.downloadCard': 'Download Battle Card', 'ui.restart': 'Restart', 'ui.backMaps': 'Back to Map Selection', 'ui.downloadError': 'Download failed: {message}. Your battle result is saved; please try again.'
  },
  ja: {
    'ui.enemySpeed': '移動速度',
    'ui.language': '言語', 'ui.brand': '星域防線', 'ui.game': 'ゲーム', 'ui.home': 'ホーム', 'ui.lead': '地上ルートと空路を進む機械群から、人類の星間コロニーのエネルギーコアを守ろう。', 'ui.start': 'ゲーム開始', 'ui.audioHint': '🔈 クリックまたはキー入力で音楽と効果音を有効にします',
    'ui.music': '音楽', 'ui.sfx': '効果音', 'ui.musicVolume': '音楽音量', 'ui.sfxVolume': '効果音音量', 'ui.selectTower': 'タワー選択', 'ui.cancel': 'キャンセル', 'ui.nextWave': '次のウェーブ', 'ui.pause': '一時停止', 'ui.speed': '速度', 'ui.install': 'アプリをインストール', 'ui.offlineReady': 'オフラインでプレイできます',
    'ui.mapSelect': 'マップ選択', 'ui.chooseMap': 'マップを選択', 'ui.wavesTitle': 'ウェーブ', 'ui.baseTitle': '♥ 基地', 'ui.resourcesTitle': '資源', 'ui.pauseResume': '一時停止／再開（P）', 'ui.startNextWave': '次のウェーブを開始（Space）', 'ui.mapButton': 'マップ', 'ui.towerMenu': 'タワーメニュー', 'ui.stars': '{count} 星',
    'ui.cost': 'コスト', 'ui.target': '対象', 'ui.detectAir': '（索敵可能）', 'ui.range': '射程', 'ui.attackRange': '攻撃 {range} マス／索敵 {detect} マス', 'ui.rangeValue': '{range} マス', 'ui.damage': 'ダメージ', 'ui.damageRate': '{interval} 秒あたり {damage}', 'ui.droneDamageRate': '{interval} 秒あたり {damage}（各機、{drones} 機）', 'ui.effect': '効果', 'ui.appearance': '特徴', 'ui.level': 'レベル', 'ui.invested': 'Lv{level} / Lv{max}（投資 {amount} CR）', 'ui.nextLevel': '次のレベル', 'ui.nextStats': 'ダメージ {damage}→{nextDamage}、射程 {range}→{nextRange} マス',
    'ui.groundShort': '地', 'ui.airShort': '空', 'ui.bothShort': '地空', 'ui.selected': '選択中', 'ui.movingLevel': '移動中・Lv{level}', 'ui.builtLevel': '建設済み・Lv{level}', 'ui.placeHint': '左クリックで設置（2×2マス）・Shift＋クリックで連続設置・Esc／右クリックで取消', 'ui.moveHint': '左クリックで移動先を選択（{cost} CR；レベル維持、移動後すぐ攻撃可能）・V／Esc／右クリックで取消', 'ui.maxLevel': '最大レベル', 'ui.upgrade': 'Lv{level} に強化（{cost} CR）', 'ui.move': '移動 {cost} CR', 'ui.sell': '売却 +{refund} CR', 'ui.instructions': '操作方法', 'ui.instructionsBuild': '上からタワーを選択（または1–0、-、=キー）し、建設可能なタイルをクリック。タワーは2×2マスです。', 'ui.instructionsRoutes': '実線の道＝地上ルート、点線と影＝空路、◇＝地空共用区間。入口にカーソルを合わせると全ルートを表示します。', 'ui.instructionsTerrain': '斜線は辺境、模様のあるマスは地形で、どちらも建設不可。迷彩敵はT05の6.0マス以内で検知できます。', 'ui.instructionsKeys': 'Space 次ウェーブ・P 停止・F 速度・U 強化・V 移動・S 売却・M 音楽・N 効果音',
    'ui.pausedStatus': '⏸ 一時停止中 — 建設は可能です。Pまたは速度ボタンで再開', 'ui.waveStartFirst': '第1ウェーブ開始', 'ui.waveFinal': '最終ウェーブ', 'ui.waveStartNext': '次のウェーブ', 'ui.audioOn': 'オン', 'ui.audioOff': 'オフ', 'ui.audioToggleTitle': '{name}：{state}（{key}で切替）', 'ui.audioVolumeTitle': '{name} 音量 {percent}%',
    'ui.hp': '耐久', 'ui.shield': 'シールド', 'ui.type': 'タイプ', 'ui.childType': '{type}（分裂体）', 'ui.speedRate': '{speed} マス／秒', 'ui.reward': '報酬', 'ui.childReward': '0 CR（分裂体）', 'ui.route': 'ルート {id}', 'ui.airRoute': '空路（点線）', 'ui.groundRoute': '地上ルート（実線）', 'ui.routeHighlight': '全経路を表示中',
    'ui.errFunds': '資源不足', 'ui.errEnded': 'ゲーム終了', 'ui.errMove': 'ここには移動できません', 'ui.errBuild': 'ここには建設できません', 'ui.errMax': '最大レベルです', 'ui.sold': '売却しました。返金 {refund} CR', 'ui.victory': '✔ 勝利', 'ui.defeat': '✖ 敗北', 'ui.downloadCard': '戦績カードをダウンロード', 'ui.restart': '再スタート', 'ui.backMaps': 'マップ選択へ戻る', 'ui.downloadError': 'ダウンロード失敗：{message}。戦績は保存されています。再試行してください。'
  },
  ko: {
    'ui.enemySpeed': '이동 속도',
    'ui.language': '언어', 'ui.brand': '성역 방어선', 'ui.game': '전투', 'ui.home': '홈', 'ui.lead': '지상 경로와 공중 항로로 진격하는 기계 군단으로부터 인류 성간 식민지의 에너지 코어를 지키세요.', 'ui.start': '게임 시작', 'ui.audioHint': '🔈 아무 곳이나 클릭하거나 키를 눌러 음악과 효과음을 켜세요',
    'ui.music': '음악', 'ui.sfx': '효과음', 'ui.musicVolume': '음악 음량', 'ui.sfxVolume': '효과음 음량', 'ui.selectTower': '타워 선택', 'ui.cancel': '취소', 'ui.nextWave': '다음 웨이브', 'ui.pause': '일시 정지', 'ui.speed': '속도', 'ui.install': '앱 설치', 'ui.offlineReady': '오프라인 플레이 준비 완료',
    'ui.mapSelect': '맵 선택', 'ui.chooseMap': '맵 선택하기', 'ui.wavesTitle': '웨이브', 'ui.baseTitle': '♥ 기지', 'ui.resourcesTitle': '자원', 'ui.pauseResume': '일시 정지／재개（P）', 'ui.startNextWave': '다음 웨이브 시작（Space）', 'ui.mapButton': '맵', 'ui.towerMenu': '타워 메뉴', 'ui.stars': '{count}개 별',
    'ui.cost': '비용', 'ui.target': '대상', 'ui.detectAir': '（은신 감지）', 'ui.range': '사거리', 'ui.attackRange': '공격 {range}칸／감지 {detect}칸', 'ui.rangeValue': '{range}칸', 'ui.damage': '피해', 'ui.damageRate': '{interval}초당 {damage}', 'ui.droneDamageRate': '{interval}초당 {damage}（기체당, {drones}기）', 'ui.effect': '효과', 'ui.appearance': '특징', 'ui.level': '레벨', 'ui.invested': 'Lv{level} / Lv{max}（투자 {amount} CR）', 'ui.nextLevel': '다음 레벨', 'ui.nextStats': '피해 {damage}→{nextDamage}, 사거리 {range}→{nextRange}칸',
    'ui.groundShort': '지', 'ui.airShort': '공', 'ui.bothShort': '지공', 'ui.selected': '선택됨', 'ui.movingLevel': '이동 중 · Lv{level}', 'ui.builtLevel': '건설됨 · Lv{level}', 'ui.placeHint': '왼쪽 클릭으로 배치（2×2칸）· Shift＋클릭 연속 배치 · Esc／오른쪽 클릭 취소', 'ui.moveHint': '왼쪽 클릭으로 새 위치 선택（{cost} CR; 레벨 유지, 이동 직후 공격 가능）· V／Esc／오른쪽 클릭 취소', 'ui.maxLevel': '최고 레벨', 'ui.upgrade': 'Lv{level}로 업그레이드（{cost} CR）', 'ui.move': '이동 {cost} CR', 'ui.sell': '판매 +{refund} CR', 'ui.instructions': '조작 안내', 'ui.instructionsBuild': '위에서 타워를 선택（또는 1–0, -, =）하고 건설 가능한 타일을 클릭하세요. 타워는 2×2칸을 차지합니다.', 'ui.instructionsRoutes': '실선 도로＝지상 경로, 점선과 그림자＝공중 항로, ◇＝지상/공중 공용 구간. 입구에 마우스를 대면 전체 경로가 강조됩니다.', 'ui.instructionsTerrain': '빗금은 변방, 무늬 타일은 테마 지형이며 모두 건설할 수 없습니다. 은신 적은 T05가 6.0칸 이내에서 감지합니다.', 'ui.instructionsKeys': 'Space 다음 웨이브 · P 일시 정지 · F 속도 · U 업그레이드 · V 이동 · S 판매 · M 음악 · N 효과음',
    'ui.pausedStatus': '⏸ 일시 정지 — 타워 건설은 가능합니다. P 또는 속도 버튼으로 재개', 'ui.waveStartFirst': '1 웨이브 시작', 'ui.waveFinal': '마지막 웨이브', 'ui.waveStartNext': '다음 웨이브 시작', 'ui.audioOn': '켜짐', 'ui.audioOff': '꺼짐', 'ui.audioToggleTitle': '{name}: {state}（{key} 키로 전환）', 'ui.audioVolumeTitle': '{name} 음량 {percent}%',
    'ui.hp': '체력', 'ui.shield': '보호막', 'ui.type': '유형', 'ui.childType': '{type}（분열 개체）', 'ui.speedRate': '{speed}칸／초', 'ui.reward': '보상', 'ui.childReward': '0 CR（분열 개체）', 'ui.route': '경로 {id}', 'ui.airRoute': '공중 항로（점선）', 'ui.groundRoute': '지상 경로（실선 도로）', 'ui.routeHighlight': '전체 이동 경로 강조됨',
    'ui.errFunds': '자원이 부족합니다', 'ui.errEnded': '게임이 종료되었습니다', 'ui.errMove': '이곳으로 이동할 수 없습니다', 'ui.errBuild': '이곳에는 건설할 수 없습니다', 'ui.errMax': '최고 레벨입니다', 'ui.sold': '판매 완료, {refund} CR 환불', 'ui.victory': '✔ 승리', 'ui.defeat': '✖ 패배', 'ui.downloadCard': '전투 결과 카드 다운로드', 'ui.restart': '다시 시작', 'ui.backMaps': '맵 선택으로 돌아가기', 'ui.downloadError': '다운로드 실패: {message}. 전투 결과는 저장되었습니다. 다시 시도하세요.'
  }
};
